### ISSUE TITLE
authentication check fails with Could not find a declaration file for module 'lit-html/lib/shady-render.js'.

### ISSUE THREAD

**Issue by zebak007** [amrutha95/Mgt-Electron-Provider-Demo#1]
Did follow the blog below but failing at authentication check. 
https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-mailbag-microsoft-graph-in-electron-applications-using-microsoft-graph-toolkit/

Getting the following error message in VSCode

Could not find a declaration file for module 'lit-html/lib/shady-render.js'. 'c:/GitHub/electron-quick-start-typescript/node_modules/lit-html/lib/shady-render.js' implicitly has an 'any' type.

**Comment by amrutha95** [comment]
Hi @zebak007! Can you try setting ```noImplicitAny``` to ```false``` under ```compilerOptions``` in your tsconfig.json?

**Comment by cbezenco** [comment]
Thanks, issue solved.
